# .github/workflows/android.yml
name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install JS dependencies
        run: |
          cd ./nexus-life-ops
          npm install

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Build Android release
        run: |
          cd ./nexus-life-ops/android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: nexus-life-ops/android/app/build/outputs/apk/release/app-release.apk
