.github/workflows/android.yml

name: Build Android APK

on: push: branches: - main

jobs: build: name: Génération APK Release runs-on: ubuntu-latest env: ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

steps:
  - name: Checkout repo
    uses: actions/checkout@v3

  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: '11'

  - name: Install Android SDK
    run: |
      mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
      cd "$ANDROID_SDK_ROOT/cmdline-tools"
      wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
      unzip cmdline-tools.zip -d latest
      rm cmdline-tools.zip
      yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
        "platform-tools" "platforms;android-31" "build-tools;31.0.0"

  - name: Cache Gradle
    uses: actions/cache@v3
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      restore-keys: |
        ${{ runner.os }}-gradle-

  - name: Install Node.js dependencies
    run: npm install

  - name: Build Release APK
    run: npx react-native run-android --variant=release

  - name: Upload APK artifact
    uses: actions/upload-artifact@v3
    with:
      name: app-release.apk
      path: android/app/build/outputs/apk/release/app-release.apk
