GitHub Actions workflow for Nexus Life Ops Android APK

name: Build Android APK

on: push: branches: - main

jobs: build: runs-on: ubuntu-latest

env:
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      distribution: temurin
      java-version: '11'

  - name: Install Android SDK command-line tools
    run: |
      mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
      curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
      unzip cmdline-tools.zip -d cmdline-tools
      mv cmdline-tools/cmdline-tools latest
      rm cmdline-tools.zip
      yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
        "platform-tools" "platforms;android-31" "build-tools;31.0.0"

  - name: Cache Gradle
    uses: actions/cache@v3
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      restore-keys: |
        ${{ runner.os }}-gradle-

  - name: Install Node.js dependencies
    run: npm ci

  - name: Build Android Release
    run: |
      cd android
      ./gradlew assembleRelease

  - name: Upload APK artifact
    uses: actions/upload-artifact@v3
    with:
      name: app-release.apk
      path: android/app/build/outputs/apk/release/app-release.apk
