name: CI/CD & Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint, Test & Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint "**/*.js" "**/*.jsx" --max-warnings=0

      - name: Run Prettier write
        run: npx prettier --write "**/*.{js,jsx,json,md,yml,yaml}"

      - name: Commit formatted code
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: apply Prettier formatting" || echo "No changes to commit"
          git push

      - name: Run Jest unit tests
        run: npx jest --ci --coverage

      - name: Run Snyk vulnerability scan
        uses: snyk/actions/node@master
        with:
          args: test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
